name = "Senciro"
uuid = "a5aa4c8c-878b-4250-8f20-feefce0a5039"
version = "0.1.0"
authors = ["AbrJA <abraham.jaimes.mx@gmail.com>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
PicoHTTPParser = "7dfb699f-0de3-4c94-bc59-7670dfa845e2"

[compat]
JSON = "1"
julia = "1"

[extras]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "HTTP"]
