name = "Senciro"
uuid = "a5aa4c8c-878b-4250-8f20-feefce0a5039"
authors = ["AbrJA <abraham.jaimes.mx@gmail.com>"]
version = "0.1.0"

[deps]
PicoHTTPParser = "7dfb699f-0de3-4c94-bc59-7670dfa845e2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
